data:
  data_location: Synth
  extension: "wav"

preprocess:
  sample_rate: &samplerate 16000
  signal_length: &signallength 64000
  block_size: &blocksize 160 # must be a power of 2 if using realtime

  oneshot: false # crop every audio file to exactly signal length
  out_dir: ./preprocessed/

model:
  hidden_size: 512
  n_harmonic: 100
  n_bands: 65
  sample_rate: *samplerate
  block_size: *blocksize
  n_fft: 2048
  num_mfccs: 30
  z_dim: 16
  device: cpu

train:
  scales: [4096, 2048, 1024, 512, 256, 128]
  overlap: .75

hyperparams:
    batch_size: 16
